### ISSUE TITLE
Accounts - Facebook, preferred email

### ISSUE THREAD

**Issue by dpdonohue** [biologio/biolog#17]
Let's add Facebook.  Any others?  Twitter?
Also ability to link their accounts so they can log in with any of multiple
Should we capture a preferred email?  Probably we should

**Comment by dpdonohue** [comment]
Never mind I see Facebook and Twitter are ready to be configured.  So the work really is to capture a preferred email and to please remove login/password method of authenticating.  Does that sound reasonable?  So we require OAuth and store no login or passwords.

**Comment by dipakyadav** [comment]
No, we should not remove the login/password method, as there are many users
who doesn't wish to register with there existing fb, twitter or google
account

(function() {
    'Thanks & Regards!';
    'Dipak Yadav';
    'https://github.com/dipakdotyadav';

})();

**Comment by dpdonohue** [comment]
OK good advice.


On Tue, May 12, 2015 at 9:52 AM, dipakyadav <notifications@github.com>
wrote:

> No, we should not remove the login/password method, as there are many users
> who doesn't wish to register with there existing fb, twitter or google
> account
>
> (function() {
> 'Thanks & Regards!';
> 'Dipak Yadav';
> 'https://github.com/dipakdotyadav';
>
> })();
>
> On Tue, May 12, 2015 at 3:50 PM, David Donohue <notifications@github.com>
> wrote:
>
> > Never mind I see Facebook and Twitter are ready to be configured. So the
> > work really is to capture a preferred email and to please remove
> > login/password method of authenticating. Does that sound reasonable? So
> we
> > require OAuth and store no login or passwords.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/biologio/biolog/issues/17#issuecomment-101223728>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biologio/biolog/issues/17#issuecomment-101290029>.
>



-- 
*David Donohue, MD, FACP*
*Progressive Health of Delaware*
*302-543-5454*
*3519 Silverside Rd, Ste 200*
*Ridgely Bldg.*
*Wilmington, DE 19810*
*Fax 302-327-4200*
*www.progressivehealthofde.com <http://www.progressivehealthofde.com/>*

PRIVILEGED AND CONFIDENTIAL:  This document and the information contained
herein are confidential and protected from disclosure pursuant to federal
law.  This message is intended only for the use of the Addressee(s) and may
contain information that is PRIVILEGED and CONFIDENTIAL. If you are not the
intended recipient, you are hereby notified that the use dissemination, or
copying of this information is strictly prohibited.  If you have received
this communication in error, please erase all copies of the message and its
attachments and notify the sender immediately.
