### ISSUE TITLE
accounts-ui, Google authentication

### ISSUE THREAD

**Issue by dpdonohue** [biologio/biolog#2]
This is dead simple and requires just a couple Meteor packages and a single line of code in the HTML template.

**Comment by dipakyadav** [comment]
i think this is fixed now ?

**Comment by dpdonohue** [comment]
great!  Could you move Medicines and Admin to the side menu?
The side menu gives key pages one would want to visit:
Conditions, Medications, Events, Timeline
Top menu should show logo on left, who is the patient in center, and who is the user at right.
Tapping on the patient or the user allows the user to select a different patient or a different user.
